project:
  type: website
website:
  title: "Как перестать быть папуасом?"
  navbar:
    left:
      - href: index.qmd
        text: Посты
      - about.qmd
  
format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    lang: ru
